

--RESORTs
INSERT INTO resort VALUES (1, 'Parkhouse Byron Bay Resort', '55 Lawson St', '2481', null, 'N', 1, 4);
INSERT INTO resort VALUES (2, 'Golden Mudgee Resort', '44 Mortimer St', '2850', null, 'N', 2, 4);
INSERT INTO resort VALUES (3, 'Rivera Kingaroy Resort', '10 Somerset St', '4610', null, 'N', 3, 5);
INSERT INTO resort VALUES (4, 'Avenue Gympie Resort', '210 Brisbane Rd', '4570', null, 'N', 4, 5);
INSERT INTO resort VALUES (5, 'Ruffalo Alice Springs Resort', '49 Stuart Hwy', '0870', null, 'Y', 5, 3);
INSERT INTO resort VALUES (6, 'Downey Broome Resort', '57 Robinson St', '6725', null, 'N', 6, 1);
INSERT INTO resort VALUES (7, 'Hail Mt Isa Resort', '75 Deighton St', '4825', null, 'N', 7, 5);
INSERT INTO resort VALUES (8, 'Felix Taree Resort', '80 Victoria St', '2430', null, 'Y', 8, 4);
INSERT INTO resort VALUES (9, 'Phoenix Echuca Resort', '42 Crofton St', '3564', null, 'N', 9, 4);
INSERT INTO resort VALUES (10, 'Guardiola Tanami Resort', 'Tanami Desert located in NT', '0872', null, 'N', 10, 3);
INSERT INTO resort VALUES (11, 'Mix Taabinga Resort', '4 Kingaroy Burrandowan Rd', '4610', null, 'N', 11, 5);
INSERT INTO resort VALUES (12, 'Ole Mothar Mountain Resort', '270 Hill Rd', '4571', null, 'N', 12, 5);
INSERT INTO resort VALUES (13, 'Little Stuart Resort', '20 Ulpaya Rd', '0870', null, 'N', 13, 3);
INSERT INTO resort VALUES (14, 'Wild Mornington Resort', '2 Lardil St', '4892', null, 'N', 14, 5);
INSERT INTO resort VALUES (15, 'Mind The Gap Resort', '91 Payne Rd', '4061', null, 'N', 15, 5);
INSERT INTO resort VALUES (16, 'Trump Sturt Creek', 'Carranya-Wolfe Creek Crater Rd', '6770', null, 'N', 16, 1);
INSERT INTO resort VALUES (17, 'Great Bunya Mountains Resort', 'Bunya Ave', '4405', null, 'N', 17, 5);
INSERT INTO resort VALUES (18, 'Rocky Halls Creek', '110 Roberta Ave', '6770', null, 'N', 18, 1);

--CABINs
INSERT INTO cabin VALUES (1, 1, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 1, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 1, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (4, 1, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (5, 1, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (6, 1, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (7, 1, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (8, 1, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (9, 1, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (10, 1, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (11, 1, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (12, 1, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 2, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 2, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 2, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 3, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 3, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 3, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (4, 3, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (5, 3, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (6, 3, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (7, 3, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (8, 3, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (9, 3, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (10, 3, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 4, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 4, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 4, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (4, 4, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (5, 4, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (6, 4, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 5, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 5, 3, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 5, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (4, 5, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 6, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 6, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 6, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (4, 6, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 7, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 7, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 7, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 8, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 8, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 8, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (4, 8, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 9, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 9, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 9, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 10, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 10, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 10, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 11, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 11, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 11, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 12, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 12, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 12, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 13, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 13, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 13, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 14, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 14, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 14, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 15, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 15, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 15, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (4, 15, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (5, 15, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (6, 15, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 16, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 16, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 16, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 17, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 17, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 17, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (1, 18, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (2, 18, 3, 6, 'Free Wi-Fi, Kitchen with 400 ltr refrigerator, stove, microwave, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (3, 18, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');
INSERT INTO cabin VALUES (4, 18, 2, 4, 'Free Wi-Fi, Kitchen with 280 ltr refrigerator, stove, pots, pans, silverware, toaster, electric kettle, TV and utensils');

--BOOKINGs
INSERT INTO booking VALUES (1, TO_DATE('02-Oct-2019','DD-Mon-YYYY'), TO_DATE('05-Oct-2019','DD-Mon-YYYY'), 2, 2, 950.65, 6, 8, 3);
INSERT INTO booking VALUES (2, TO_DATE('02-Oct-2019','DD-Mon-YYYY'), TO_DATE('04-Oct-2019','DD-Mon-YYYY'), 4, 0, 350.55, 2, 3, 5);
INSERT INTO booking VALUES (3, TO_DATE('03-Oct-2019','DD-Mon-YYYY'), TO_DATE('05-Oct-2019','DD-Mon-YYYY'), 3, 0, 350.12, 5, 6, 4);
INSERT INTO booking VALUES (4, TO_DATE('03-Oct-2019','DD-Mon-YYYY'), TO_DATE('06-Oct-2019','DD-Mon-YYYY'), 6, 0, 650.14, 9, 1, 3);
INSERT INTO booking VALUES (5, TO_DATE('03-Oct-2019','DD-Mon-YYYY'), TO_DATE('06-Oct-2019','DD-Mon-YYYY'), 2, 2, 650.83, 1, 2, 7);
INSERT INTO booking VALUES (6, TO_DATE('04-Oct-2019','DD-Mon-YYYY'), TO_DATE('06-Oct-2019','DD-Mon-YYYY'), 2, 1, 350.62, 3, 2, 11);
INSERT INTO booking VALUES (7, TO_DATE('06-Oct-2019','DD-Mon-YYYY'), TO_DATE('10-Oct-2019','DD-Mon-YYYY'), 2, 4, 1600.12, 8, 2, 1);
INSERT INTO booking VALUES (8, TO_DATE('06-Oct-2019','DD-Mon-YYYY'), TO_DATE('08-Oct-2019','DD-Mon-YYYY'), 3, 2, 1100.00, 10, 1, 15);
INSERT INTO booking VALUES (9, TO_DATE('07-Oct-2019','DD-Mon-YYYY'), TO_DATE('11-Oct-2019','DD-Mon-YYYY'), 2, 2, 650.21, 3, 4, 18);
INSERT INTO booking VALUES (10, TO_DATE('10-Oct-2019','DD-Mon-YYYY'), TO_DATE('12-Oct-2019','DD-Mon-YYYY'), 2, 1, 354.24, 1, 2, 14);
INSERT INTO booking VALUES (11, TO_DATE('10-Oct-2019','DD-Mon-YYYY'), TO_DATE('13-Oct-2019','DD-Mon-YYYY'), 3, 0, 652.10, 10, 2, 6);
INSERT INTO booking VALUES (12, TO_DATE('14-Oct-2019','DD-Mon-YYYY'), TO_DATE('18-Oct-2019','DD-Mon-YYYY'), 4, 0, 550.05, 5, 1, 2);
INSERT INTO booking VALUES (13, TO_DATE('14-Oct-2019','DD-Mon-YYYY'), TO_DATE('17-Oct-2019','DD-Mon-YYYY'), 2, 1, 650.15, 9, 4, 8);
INSERT INTO booking VALUES (14, TO_DATE('15-Oct-2019','DD-Mon-YYYY'), TO_DATE('18-Oct-2019','DD-Mon-YYYY'), 4, 0, 650.12, 8, 11, 1);
INSERT INTO booking VALUES (15, TO_DATE('16-Oct-2019','DD-Mon-YYYY'), TO_DATE('20-Oct-2019','DD-Mon-YYYY'), 4, 2, 1600.13, 6, 2, 15);
INSERT INTO booking VALUES (16, TO_DATE('17-Oct-2019','DD-Mon-YYYY'), TO_DATE('19-Oct-2019','DD-Mon-YYYY'), 2, 1, 350.14, 2, 2, 12);
INSERT INTO booking VALUES (17, TO_DATE('18-Oct-2019','DD-Mon-YYYY'), TO_DATE('22-Oct-2019','DD-Mon-YYYY'), 3, 2, 1622.20, 1, 4, 3);
INSERT INTO booking VALUES (18, TO_DATE('18-Oct-2019','DD-Mon-YYYY'), TO_DATE('20-Oct-2019','DD-Mon-YYYY'), 3, 2, 1500.00, 9, 1, 17);
INSERT INTO booking VALUES (19, TO_DATE('18-Oct-2019','DD-Mon-YYYY'), TO_DATE('21-Oct-2019','DD-Mon-YYYY'), 2, 1, 650.30, 10, 2, 16);
INSERT INTO booking VALUES (20, TO_DATE('19-Oct-2019','DD-Mon-YYYY'), TO_DATE('23-Oct-2019','DD-Mon-YYYY'), 3, 0, 550.10, 3, 3, 13);
INSERT INTO booking VALUES (21, TO_DATE('21-Oct-2019','DD-Mon-YYYY'), TO_DATE('23-Oct-2019','DD-Mon-YYYY'), 2, 2, 350.70, 2, 2, 12);
INSERT INTO booking VALUES (22, TO_DATE('21-Oct-2019','DD-Mon-YYYY'), TO_DATE('24-Oct-2019','DD-Mon-YYYY'), 3, 0, 650.65, 6, 2, 9);
INSERT INTO booking VALUES (23, TO_DATE('22-Oct-2019','DD-Mon-YYYY'), TO_DATE('26-Oct-2019','DD-Mon-YYYY'), 2, 4, 1600.05, 9, 5, 1);
INSERT INTO booking VALUES (24, TO_DATE('24-Oct-2019','DD-Mon-YYYY'), TO_DATE('27-Oct-2019','DD-Mon-YYYY'), 2, 2, 650.00, 8, 2, 2);
INSERT INTO booking VALUES (25, TO_DATE('24-Oct-2019','DD-Mon-YYYY'), TO_DATE('26-Oct-2019','DD-Mon-YYYY'), 3, 2, 1200.10, 1, 5, 3);
INSERT INTO booking VALUES (26, TO_DATE('24-Oct-2019','DD-Mon-YYYY'), TO_DATE('28-Oct-2019','DD-Mon-YYYY'), 4, 2, 1600.00, 10, 4, 1);
INSERT INTO booking VALUES (27, TO_DATE('26-Oct-2019','DD-Mon-YYYY'), TO_DATE('29-Oct-2019','DD-Mon-YYYY'), 4, 0, 950.30, 6, 8, 3);
INSERT INTO booking VALUES (28, TO_DATE('26-Oct-2019','DD-Mon-YYYY'), TO_DATE('30-Oct-2019','DD-Mon-YYYY'), 3, 0, 950.25, 3, 4, 15);
INSERT INTO booking VALUES (29, TO_DATE('27-Oct-2019','DD-Mon-YYYY'), TO_DATE('29-Oct-2019','DD-Mon-YYYY'), 2, 2, 350.10, 5, 4, 4);
INSERT INTO booking VALUES (30, TO_DATE('27-Oct-2019','DD-Mon-YYYY'), TO_DATE('29-Oct-2019','DD-Mon-YYYY'), 2, 2, 350.40, 2, 4, 5);


--REVIEWs
INSERT INTO review VALUES (1, 'enjoyable stay', TO_DATE('05-Oct-2019','DD-Mon-YYYY'), 4, 2, 5);
INSERT INTO review VALUES (2, 'excellent', TO_DATE('06-Oct-2019','DD-Mon-YYYY'), 5, 5, 4);
INSERT INTO review VALUES (3, 'lonely location', TO_DATE('07-Oct-2019','DD-Mon-YYYY'), 2, 7, 16);
INSERT INTO review VALUES (4, 'very bad', TO_DATE('07-Oct-2019','DD-Mon-YYYY'), 1, 7, 10);
INSERT INTO review VALUES (5, 'will not come back', TO_DATE('07-Oct-2019','DD-Mon-YYYY'), 2, 1, 7);
INSERT INTO review VALUES (6, 'very pleasant staffs', TO_DATE('09-Oct-2019','DD-Mon-YYYY'), 4, 10, 15);
INSERT INTO review VALUES (7, 'clean place', TO_DATE('10-Oct-2019','DD-Mon-YYYY'), 5, 6, 3);
INSERT INTO review VALUES (8, 'fantastic experience...', TO_DATE('11-Oct-2019','DD-Mon-YYYY'), 5, 8, 1);
INSERT INTO review VALUES (9, 'bad quality accomodation', TO_DATE('11-Oct-2019','DD-Mon-YYYY'), 1, 1, 14);
INSERT INTO review VALUES (10, 'looking forward to coming again;p', TO_DATE('13-Oct-2019','DD-Mon-YYYY'), 2, 4, 10);
INSERT INTO review VALUES (11, 'terrible service:(', TO_DATE('14-Oct-2019','DD-Mon-YYYY'), 1, 10, 6);
INSERT INTO review VALUES (12, 'lots of great things to do', TO_DATE('19-Oct-2019','DD-Mon-YYYY'), 4, 8, 1);
INSERT INTO review VALUES (13, 'great location', TO_DATE('21-Oct-2019','DD-Mon-YYYY'), 5, 6, 15);
INSERT INTO review VALUES (14, 'amazing view :)', TO_DATE('21-Oct-2019','DD-Mon-YYYY'), 5, 9, 17);
INSERT INTO review VALUES (15, 'nothing much to do', TO_DATE('22-Oct-2019','DD-Mon-YYYY'), 2, 10, 16);
INSERT INTO review VALUES (16, 'should try', TO_DATE('24-Oct-2019','DD-Mon-YYYY'), 4, 2, 12);
INSERT INTO review VALUES (17, 'beautiful place', TO_DATE('24-Oct-2019','DD-Mon-YYYY'), 4, 3, 13);
INSERT INTO review VALUES (18, 'meets expectation', TO_DATE('24-Oct-2019','DD-Mon-YYYY'), 3, 1, 3);
INSERT INTO review VALUES (19, 'looks good!!', TO_DATE('27-Oct-2019','DD-Mon-YYYY'), 4, 9, 1);
INSERT INTO review VALUES (20, 'had lots of fun', TO_DATE('27-Oct-2019','DD-Mon-YYYY'), 4, 8, 2);
INSERT INTO review VALUES (21, 'bad service!!', TO_DATE('27-Oct-2019','DD-Mon-YYYY'), 2, 1, 3);
INSERT INTO review VALUES (22, 'friendly and helpful staffs', TO_DATE('29-Oct-2019','DD-Mon-YYYY'), 4, 10, 1);
INSERT INTO review VALUES (23, 'luxurious', TO_DATE('30-Oct-2019','DD-Mon-YYYY'), 5, 6, 3);
INSERT INTO review VALUES (24, 'cheap!!', TO_DATE('30-Oct-2019','DD-Mon-YYYY'), 3, 5, 4);
INSERT INTO review VALUES (25, 'value for money', TO_DATE('31-Oct-2019','DD-Mon-YYYY'), 4, 2, 5);

--update resort star_rating

update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 1) where resort_id = 1;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 2) where resort_id = 2;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 3) where resort_id = 3;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 4) where resort_id = 4;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 5) where resort_id = 5;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 6) where resort_id = 6;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 7) where resort_id = 7;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 8) where resort_id = 8;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 9) where resort_id = 9;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 10) where resort_id = 10;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 11) where resort_id = 11;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 12) where resort_id = 12;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 13) where resort_id = 13;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 14) where resort_id = 14;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 15) where resort_id = 15;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 16) where resort_id = 16;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 17) where resort_id = 17;
update resort set resort_star_rating = (select round(avg(nvl(review_rating, 0)),1) from review where resort_id = 18) where resort_id = 18;	

-- COMMIT inserted data
commit;
